apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
spec:
  template:
    spec:
      containers:
      - name: mongo-init
        image: mongo:latest
        command: ["sh", "-c", "mongosh --host mongodb-service --eval 'use microserviceDB; db.createCollection(\"data\")'"]
      restartPolicy: OnFailure

---        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp-deployment
  labels:
    app: pyapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp
        image: xxdockerimage.azurecr.io/rahulwaynepyapp
        ports:
        - containerPort: 5000